### ISSUE TITLE
URL Error

### ISSUE THREAD

**Issue by Compil3-sudo** [harritaylor/torch-vggish#25]
Hello,

I just encountered this error today. Everything worked fine yesterday and now when I try to use the vggish embeddings I get this error:
```urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>```

This is what I've tried and it worked before: ```vggish_model = torch.hub.load('harritaylor/torchvggish', 'vggish')```

I am using windows 10, pycharm, python 3.8

Here is the full Traceback in case that helps:

```Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\urllib\request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\Python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files\Python38\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Program Files\Python38\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Program Files\Python38\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Program Files\Python38\lib\http\client.py", line 915, in connect
    self.sock = self._create_connection(
  File "C:\Program Files\Python38\lib\socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Program Files\Python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Bachelor Arbeit/dcase-2022-baseline-main/clotho_preprocessing.py", line 99, in <module>
    preprocess_dataset(config)
  File "D:/Bachelor Arbeit/dcase-2022-baseline-main/clotho_preprocessing.py", line 16, in preprocess_dataset
    vggish_model = torch.hub.load('harritaylor/torchvggish', 'vggish')
  File "C:\Users\tincu\AppData\Roaming\Python\Python38\site-packages\torch\hub.py", line 539, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "C:\Users\tincu\AppData\Roaming\Python\Python38\site-packages\torch\hub.py", line 180, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "C:\Users\tincu\AppData\Roaming\Python\Python38\site-packages\torch\hub.py", line 134, in _parse_repo_info
    with urlopen(f"https://github.com/{repo_owner}/{repo_name}/tree/main/"):
  File "C:\Program Files\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python38\lib\urllib\request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Program Files\Python38\lib\urllib\request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Process finished with exit code 1
```

**Comment by Compil3-sudo** [comment]
I don't know what the problem was... I think it was actually a problem with Pycharm. After I've restarted my pc it works.
